ALTER TABLE image ALTER COLUMN post_id DROP NOT NULL;

ALTER TABLE post ALTER COLUMN description TYPE VARCHAR(2000);
ALTER TABLE post
    ALTER COLUMN category TYPE VARCHAR(20),
    ALTER COLUMN category SET NOT NULL;
ALTER TABLE post
    ALTER COLUMN condition TYPE VARCHAR(10),
    ALTER COLUMN condition SET NOT NULL;
ALTER TABLE post
    ALTER COLUMN state TYPE VARCHAR(20),
    ALTER COLUMN state SET NOT NULL,
    ALTER COLUMN state SET DEFAULT 'ACTIVE';
